### PR TITLE
nsqd: BenchmarkDiskQueuePut prints errors

### PR DESCRIPTION
**Pull request by jehiah**
current master (fd6260466583555ba8e9a4884a7f39cabb36f893)
```
go test -bench=QueuePut
2015/08/06 22:54:51 http: TLS handshake error from 127.0.0.1:58649: tls: client didn't provide a certificate
2015/08/06 22:54:51 LOOKUPD: querying http://127.0.0.1:36858/channels?topic=cluster_test1438894491
PASS
BenchmarkDiskQueuePut	 1000000	      1890 ns/op	 541.51 MB/s
--- BENCH: BenchmarkDiskQueuePut
	nsqd_test.go:57: DISKQUEUE(bench_disk_queue_put11438894496): writeOne() opened /tmp/nsq-test-1438894496364087961502926977/bench_disk_queue_put11438894496.diskqueue.000000.dat
	nsqd_test.go:57: ERROR: reading from diskqueue(bench_disk_queue_put11438894496) at 0 of /tmp/nsq-test-1438894496364087961502926977/bench_disk_queue_put11438894496.diskqueue.000000.dat - open /tmp/nsq-test-1438894496364087961502926977/bench_disk_queue_put11438894496.diskqueue.000000.dat: no such file or directory
	nsqd_test.go:57: NOTICE: diskqueue(bench_disk_queue_put11438894496) jump to next file and saving bad file as /tmp/nsq-test-1438894496364087961502926977/bench_disk_queue_put11438894496.diskqueue.000000.dat.bad
	nsqd_test.go:57: ERROR: diskqueue(bench_disk_queue_put11438894496) failed to rename bad diskqueue file /tmp/nsq-test-1438894496364087961502926977/bench_disk_queue_put11438894496.diskqueue.000000.dat to /tmp/nsq-test-1438894496364087961502926977/bench_disk_queue_put11438894496.diskqueue.000000.dat.bad
	nsqd_test.go:57: ERROR: diskqueue(bench_disk_queue_put11438894496) failed to sync - open /tmp/nsq-test-1438894496364087961502926977/bench_disk_queue_put11438894496.diskqueue.meta.dat.9207838268526566190.tmp: no such file or directory
	nsqd_test.go:57: DISKQUEUE(bench_disk_queue_put1001438894496): writeOne() opened /tmp/nsq-test-1438894496365062063838665708/bench_disk_queue_put1001438894496.diskqueue.000000.dat
	nsqd_test.go:57: DISKQUEUE(bench_disk_queue_put1001438894496): readOne() opened /tmp/nsq-test-1438894496365062063838665708/bench_disk_queue_put1001438894496.diskqueue.000000.dat
	nsqd_test.go:57: DISKQUEUE(bench_disk_queue_put100001438894496): writeOne() opened /tmp/nsq-test-1438894496366220971090229851/bench_disk_queue_put100001438894496.diskqueue.000000.dat
	nsqd_test.go:57: DISKQUEUE(bench_disk_queue_put100001438894496): readOne() opened /tmp/nsq-test-1438894496366220971090229851/bench_disk_queue_put100001438894496.diskqueue.000000.dat
	nsqd_test.go:57: ERROR: diskqueue(bench_disk_queue_put100001438894496) failed to sync - open /tmp/nsq-test-1438894496366220971090229851/bench_disk_queue_put100001438894496.diskqueue.meta.dat.8974393837878367304.tmp: no such file or directory
	... [output truncated]
ok  	github.com/bitly/nsq/nsqd	9.703s

```

### CODE REVIEW

**Comment by jehiah** [comment]
@Dieterbe can you give this branch a try?

**Comment by mreiferson** [comment]
> running with GOMAXPROCS=1 go test -bench=QueuePut looks the same though :(

_exacerbated_ :grin:

**Comment by mreiferson** [comment]
@jehiah reeeeeeeeeeeeebase plz

**Comment by Dieterbe** [comment]
no errors when i run `go test -bench=QueuePut` in jehiah/diskqueue_bench_cleanup_619
but i'm also getting suspiciously fast performance
```
BenchmarkDiskQueuePut262144	   10000	      1202 ns/op	218040.76 MB/s
--- BENCH: BenchmarkDiskQueuePut262144
	nsqd_test.go:57: DISKQUEUE(bench_disk_queue_put11438956572): writeOne() opened /tmp/nsq-test-1438956572698538959368068656/bench_disk_queue_put11438956572.diskqueue.000000.dat
	nsqd_test.go:57: DISKQUEUE(bench_disk_queue_put11438956572): closing
	nsqd_test.go:57: DISKQUEUE(bench_disk_queue_put11438956572): closing ... ioLoop
	nsqd_test.go:57: DISKQUEUE(bench_disk_queue_put1001438956572): writeOne() opened /tmp/nsq-test-1438956572699759452797161935/bench_disk_queue_put1001438956572.diskqueue.000000.dat
	nsqd_test.go:57: DISKQUEUE(bench_disk_queue_put1001438956572): closing
	nsqd_test.go:57: DISKQUEUE(bench_disk_queue_put1001438956572): closing ... ioLoop
	nsqd_test.go:57: DISKQUEUE(bench_disk_queue_put100001438956572): writeOne() opened /tmp/nsq-test-1438956572700833763031899874/bench_disk_queue_put100001438956572.diskqueue.000000.dat
	nsqd_test.go:57: DISKQUEUE(bench_disk_queue_put100001438956572): closing
	nsqd_test.go:57: DISKQUEUE(bench_disk_queue_put100001438956572): closing ... ioLoop
BenchmarkDiskQueuePut1048576	   10000	      1403 ns/op	747318.37 MB/s
--- BENCH: BenchmarkDiskQueuePut1048576
	nsqd_test.go:57: DISKQUEUE(bench_disk_queue_put11438956572): writeOne() opened /tmp/nsq-test-1438956572714118434679528153/bench_disk_queue_put11438956572.diskqueue.000000.dat
	nsqd_test.go:57: DISKQUEUE(bench_disk_queue_put11438956572): closing
	nsqd_test.go:57: DISKQUEUE(bench_disk_queue_put11438956572): closing ... ioLoop
	nsqd_test.go:57: DISKQUEUE(bench_disk_queue_put1001438956572): writeOne() opened /tmp/nsq-test-1438956572715354078924973668/bench_disk_queue_put1001438956572.diskqueue.000000.dat
	nsqd_test.go:57: DISKQUEUE(bench_disk_queue_put1001438956572): closing
	nsqd_test.go:57: DISKQUEUE(bench_disk_queue_put1001438956572): closing ... ioLoop
	nsqd_test.go:57: DISKQUEUE(bench_disk_queue_put100001438956572): writeOne() opened /tmp/nsq-test-1438956572716642569946731635/bench_disk_queue_put100001438956572.diskqueue.000000.dat
	nsqd_test.go:57: DISKQUEUE(bench_disk_queue_put100001438956572): closing
	nsqd_test.go:57: DISKQUEUE(bench_disk_queue_put100001438956572): closing ... ioLoop
ok  	github.com/bitly/nsq/nsqd	7.987s
```

(i'm monitoring /tmp and it didn't fill up, in fact it looks like it's not really touched at all)

**Comment by mreiferson** [comment]
that is because it is panicing because we aren't checking errors:

```
BenchmarkDiskQueuePut1048576	panic: invalid message write size (1048576)
```

**Comment by mreiferson** [comment]
(pushed a fix)

**Comment by mreiferson** [comment]
unsurprisingly getting much more realistic numbers :grin:

```
BenchmarkDiskQueuePut1048576	    1000	   1775909 ns/op	 590.44 MB/s
```

**Pull request merged**
