### PR TITLE
nsqd: support deferred PUB

### PR DESCRIPTION
**Pull request by mreiferson**
This came up on the mailing list: https://groups.google.com/forum/#!topic/nsq-users/HkoOMygaHK0 - just opening the issue here for others to weigh in and gauge interest.

This would allow you to `PUB` a message that goes directly to the deferred priority queue with the specified delay.

Also, It's complicated a bit by #34.

### CODE REVIEW

**Comment by mreiferson** [comment]
Here goes nothing... thoughts on this approach?

**Comment by mreiferson** [comment]
(the tests are failing because of a dependency on `go-nsq` changes, which is unfortunate)

**Comment by jehiah** [comment]
actually comes out pretty cleanly. :+1:

**Comment by mreiferson** [comment]
@jehiah added HTTP support.  Note, we're explicitly not exposing deferred pub for MPUB varieties.  These tests should pass.

**Comment by jehiah** [comment]
:+1: thoughts on if/how this should be exposed in nsq_to_nsq?

**Comment by mreiferson** [comment]
> thoughts on if/how this should be exposed in nsq_to_nsq?

Do we need to support it there?  Arguably, it's already got too many knobs.  Supporting this _at all_ was already a question, having to write your own consumer to use it when copying streams around is too much to ask? :grin:

**Comment by jehiah** [comment]
Yeah i hear ya. I mean the obvious answer is it's the one spot where you would want to have a `--defer-msg=60s` type option.

Since this isn't a "reader option" it would need to be exposed directly, and we don't (yet?) support config files there so ... I'm in favor of adding there.

**Comment by jayridge** [comment]
its like christmas boys

**Comment by mreiferson** [comment]
we've been had

**Comment by zygis** [comment]
How about MDPUB or DMPUB (Multi Deferred Publish)?

**Comment by mreiferson** [comment]
@zygis I alluded to this in my comment above, but I intentionally didn't want to expose a means to defer en masse a large set of messages.  In the current implementation, `nsqd` keeps deferred messages _entirely_ in memory (i.e. they _do not_ overflow to disk).

**Comment by zygis** [comment]
Well... 
1000xDPUB - **same result** with ~1000 network calls
1xMDPUB - **same result** with ~1 network call

When deferred duration is few seconds maybe this limitation makes sence, but if duration is minutes or even hours I think this limitation solves nothing.

**Comment by mreiferson** [comment]
@zygis I realize that.  I'm concerned with the behaviors that we encourage here.  I can be convinced, it just didn't seem like the obvious use case.

**Comment by jehiah** [comment]
@zygis if the client connection buffers the socket there is little network difference between those two different protocol messages. You can pipeline a thousand DPUB just like a MDPUB would effectively provide. (there is minimal difference in command overhead between the two approaches)

**Comment by zygis** [comment]
@mreiferson I just do lot of writes to DB and via nsq notifying rest part of system do some computations. The main problem is that reads are done from slaves in other continent, and some times written data still not available, because of cross-continent replication lag. So DPUB is acceptable solution. But few weeks ago switched from PUB(client nsq.js) to MPUB(client go-nsq) because of networking problems on a servers... MDPUB could be perfect solution.

@jayridge not sure how it can be done with go-nsq client

**Comment by jehiah** [comment]
@zygis What go-nsq needs to expose for you is the equivlant of [`Producer.DeferredPublishAsync`](https://github.com/bitly/go-nsq/blob/master/producer.go#L161). The `*Async` commands allow you to pipeline multiple requests for throughput.

**Comment by zygis** [comment]
@jehiah Thanks, I will try this.

**Comment by jonathannorris** [comment]
I've been interested in using nsq for a while, we have a potential use case coming up that requires queuing of millions of deferred messages for up to a day or so. I was wondering if there are any potential performance pitfalls with this, other then nsq storing millions of messages in memory (and not backing them up on disk). It's probably not the right solution for the problem, but I'm interested to hear from @jehiah @mreiferson on this.

**Comment by ploxiln** [comment]
just a general purpose PSA: For scheduling functionality, you could use a database, with an "expires" field/column, with an index on that field/column. Have a process query the database once a minute or so for "expires < $now", process those results, then delete those rows/documents. You can limit the query to return, say, 100 results, and you can re-run the query immediately after processing&deleting if there were any results.

That's roughly what's done for a few parts of @jayridge's current project, and he grudgingly uses nsq as well anyway ;)

**Comment by mreiferson** [comment]
@jonathannorris there aren't any other performance implications, there's just the durability question.  Whether it's the right solution to the problem depends on your requirements... i.e. can you afford to lose messages that are in memory?

**Comment by mreiferson** [comment]
> That's roughly what's done for a few parts of @jayridge's current project, and he grudgingly uses nsq as well anyway ;)

I think that's a valid statement for _any_ technology @jayridge uses.

**Comment by jayridge** [comment]
true that

**Comment by captainblue2013** [comment]
So ? Can anyone tell me how to use DPUB ?
There is no concept of DPUB in  http://nsq.io/components/nsqd.html#post-pub

**Comment by mreiferson** [comment]
@captainblue2013 we should obviously document this - just pass the `?defer=x` param to `/pub`, see https://github.com/nsqio/nsq/blob/master/nsqd/http.go#L226-L237

**Comment by captainblue2013** [comment]
@mreiferson  I did it after read the source code

**Comment by kgdev** [comment]
I found a potential bug, I switched our code from using PUB to DPUB recently, and the message got handled by the client within the specified period successfully, which was good. 
However, when I check the status in localhost:4171, the "Requeued" count for that channel keeps increasing (which is not the case for PUB).

Can someone take a look into it?

image

**Comment by sakop** [comment]
@kgdev It is very easy to reproduce this bug, just exec this

``` curl -d "aDa" 'http://127.0.0.1:4151/pub?defer=1000&topic=aa'```
and you will see **Requeued** keep increasing while **Messages** remains 0

**Comment by ploxiln** [comment]
This makes sense because nsqd treats it just like a message on which the consumer called "requeue(delay=...)". It could be improved - but for that you should definitely open a new separate issue.

(Also, nsqd was not designed as a scheduling service, and thus has a few other problems with this use case.)

**Comment by kgdev** [comment]
Agree. I prefer not using "deferred" enqueue.

**Comment by mreiferson** [comment]
@kgdev I believe this accounting issue was resolved in #805

**Pull request merged**
